### ISSUE TITLE
Installation tips needed!!!

### ISSUE THREAD

**Issue by maen007** [aneek/nginx-php-drupal8-quickstart#1]
Hi @aneek,
I tried to install your drupal8 quickstart.
So what did I do:
- I loaded both cartridges nginx and php-fpm.
- Then I cloned your repo at app-root/runtime/repo/.
- I went to your quickstart.../action...., then I started with sh build and everything seems peachy.
  I opened d8-maen.rhcloud.com and get a 403.
  I made a chmod -R 775 for app-root/runtime/repo/public but this issue persists.

rhc tail d8 gives me:
==> app-root/logs/nginx_error.log <==
2016/01/24 02:38:53 [error] 115466#0: *4 directory index of "/var/lib/openshift/XXX/app-root/runtime/repo//public/" is forbidden, client: 127.5.83.129, server: , request: "GET / HTTP/1.1", host: "d8-maen.rhcloud.com"

==> app-root/logs/php-fpm-error.log <==
[24-Jan-2016 02:16:39] NOTICE: [pool www] 'user' directive is ignored when FPM is not running as root
[24-Jan-2016 02:16:39] NOTICE: [pool www] 'group' directive is ignored when FPM is not running as root
[24-Jan-2016 02:16:39] NOTICE: fpm is running, pid 123203
[24-Jan-2016 02:16:39] NOTICE: ready to handle connections
[24-Jan-2016 02:22:45] NOTICE: Terminating ...
[24-Jan-2016 02:22:45] NOTICE: exiting, bye-bye!

Do you have a hint for me???

THX in advance

maen

**Comment by aneek** [comment]
@maen007 I'll add the installation wiki instructions today. By following it you can surely install this package.
Thanks for your patience.

**Comment by aneek** [comment]
Hello @maen007 this installation instruction should get things started. Please have a look at https://github.com/aneek/nginx-php-drupal8-quickstart/wiki/Installation-Instruction
I'll add more to it and also about the directory structure of the quick start soon.

**Comment by maen007** [comment]
Cool! Works like a charme! Thank you a lot!
